### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by dflkasjfh** [brentyi/dfgo#1]
I am a newbie in python and meet this problem which shows in the following image, how can I fix it?  Thanks for any kindly help!
![image](https://user-images.githubusercontent.com/74122454/131945682-a54b48be-b611-44c4-aa3c-318e7874a165.png)

**Comment by brentyi** [comment]
Hi!

Can you try running:
```bash
pip uninstall datargs
pip install git+git://github.com/brentyi/datargs@master
```

And see if that fixes things? This looks like a `datargs` versioning issue.

**Comment by dflkasjfh** [comment]
Greate! It's useful! Thanks again!
